services:

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fiap123
      MYSQL_DATABASE: agro
      MYSQL_USER: agro
      MYSQL_PASSWORD: fiap123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts-db:/docker-entrypoint-initdb.d

      
  coleta:
    image: "seberino/coleta-api:1.0"
    container_name: coleta-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: fiap123
      DB_NAME: agro
    ports:
      - "5000:5000"

volumes:
  db_data:
    